# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cellpose_remote_pb2 as cellpose__remote__pb2


class HealthStub(object):
    """Basic health check
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/cellpose.remote.Health/Check',
                request_serializer=cellpose__remote__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=cellpose__remote__pb2.HealthCheckResponse.FromString,
                )


class HealthServicer(object):
    """Basic health check
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=cellpose__remote__pb2.HealthCheckRequest.FromString,
                    response_serializer=cellpose__remote__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cellpose.remote.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Basic health check
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cellpose.remote.Health/Check',
            cellpose__remote__pb2.HealthCheckRequest.SerializeToString,
            cellpose__remote__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileServiceStub(object):
    """File transfer to register training/inference data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/cellpose.remote.FileService/Upload',
                request_serializer=cellpose__remote__pb2.FileChunk.SerializeToString,
                response_deserializer=cellpose__remote__pb2.UploadReply.FromString,
                )
        self.Download = channel.unary_stream(
                '/cellpose.remote.FileService/Download',
                request_serializer=cellpose__remote__pb2.DownloadRequest.SerializeToString,
                response_deserializer=cellpose__remote__pb2.FileChunk.FromString,
                )


class FileServiceServicer(object):
    """File transfer to register training/inference data
    """

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=cellpose__remote__pb2.FileChunk.FromString,
                    response_serializer=cellpose__remote__pb2.UploadReply.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=cellpose__remote__pb2.DownloadRequest.FromString,
                    response_serializer=cellpose__remote__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cellpose.remote.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """File transfer to register training/inference data
    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/cellpose.remote.FileService/Upload',
            cellpose__remote__pb2.FileChunk.SerializeToString,
            cellpose__remote__pb2.UploadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cellpose.remote.FileService/Download',
            cellpose__remote__pb2.DownloadRequest.SerializeToString,
            cellpose__remote__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InferenceServiceStub(object):
    """Inference on one or more images (batch supported)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/cellpose.remote.InferenceService/Run',
                request_serializer=cellpose__remote__pb2.RunRequest.SerializeToString,
                response_deserializer=cellpose__remote__pb2.JobUpdate.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/cellpose.remote.InferenceService/ListModels',
                request_serializer=cellpose__remote__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=cellpose__remote__pb2.ListModelsResponse.FromString,
                )


class InferenceServiceServicer(object):
    """Inference on one or more images (batch supported)
    """

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=cellpose__remote__pb2.RunRequest.FromString,
                    response_serializer=cellpose__remote__pb2.JobUpdate.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=cellpose__remote__pb2.ListModelsRequest.FromString,
                    response_serializer=cellpose__remote__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cellpose.remote.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Inference on one or more images (batch supported)
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cellpose.remote.InferenceService/Run',
            cellpose__remote__pb2.RunRequest.SerializeToString,
            cellpose__remote__pb2.JobUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cellpose.remote.InferenceService/ListModels',
            cellpose__remote__pb2.ListModelsRequest.SerializeToString,
            cellpose__remote__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
