import numpy as np
import logging

logger = logging.getLogger(__name__)

def validate_visualization_mask(viz_mask: np.ndarray, original_mask: np.ndarray) -> bool:
    """
    Validates that a visualization mask is compatible with the original segmentation mask.
    
    This ensures that the visualization mask can be used in the GUI interchangeably with
    the original mask (e.g. for class-based coloring and hiding).
    
    The validation checks:
    1. Shape consistency: viz_mask must have the same shape as original_mask.
    2. Data type: viz_mask must be an integer type.
    3. ID consistency: viz_mask must only contain IDs present in original_mask (or 0).
       This ensures that looking up class information for a pixel in the visualization
       mask yields a valid class from the original segmentation's class list.

    Args:
        viz_mask (np.ndarray): The mask generated by the plugin for visualization.
        original_mask (np.ndarray): The original segmentation mask (ground truth).

    Returns:
        bool: True if the mask is valid.

    Raises:
        ValueError: If any of the validation checks fail.
    """
    # 1. Shape Check
    if viz_mask.shape != original_mask.shape:
        msg = (f"Shape mismatch: Visualization mask shape {viz_mask.shape} "
               f"does not match original mask shape {original_mask.shape}.")
        logger.error(msg)
        raise ValueError(msg)

    # 2. Data Type Check
    if not np.issubdtype(viz_mask.dtype, np.integer):
        msg = (f"Type mismatch: Visualization mask must be of integer type, "
               f"got {viz_mask.dtype}.")
        logger.error(msg)
        raise ValueError(msg)

    # 3. ID Consistency Check
    # Ensure all IDs in viz_mask exist in original_mask.
    # This is critical for 'Class View' to work correctly.
    if original_mask.size > 0 and viz_mask.size > 0:
        if viz_mask.max() > original_mask.max():
            msg = (f"ID Overflow: Visualization mask contains ID {viz_mask.max()}, "
                   f"which is larger than the maximum ID in the original mask ({original_mask.max()}).")
            logger.error(msg)
            raise ValueError(msg)

    return True